export const ACCESS_KEY = '5491';

export const TRANSLATIONS: { [key: string]: { [key: string]: string } } = {
    en: {
        deweyBrain: 'Dewey Brain',
        accessKeyTitle: '🔑 Enter Access Key',
        accessKeySubtitle: 'Enter your 4-digit access code to continue.',
        appTitle: 'Dewey Brain Interactive',
        appSubtitle: 'Intelligent DDC Classification Assistant',
        tabGenerate: 'Generate DDC',
        tabVerify: 'Verify DDC',
        ddcEdition: 'DDC Edition',
        autoDetect: 'Auto-Detect',
        titleSubject: 'Title / Subject',
        titlePlaceholder: 'e.g., A History of Chemistry in Germany',
        ddcNumberToVerify: 'DDC Number to Verify',
        ddcPlaceholder: 'e.g., 540.943',
        instructionHint: 'Instruction or Hint',
        hintPlaceholder: 'e.g., research paper, focus on Pakistan',
        generateDDCNumber: '✨ Generate DDC Number',
        verifyDDCNumber: '✔️ Verify DDC Number',
        clear: 'Clear',
        analyzing: 'Analyzing with AI...',
        fetchingLOD: 'Fetching Library Data...',
        debating: 'AI Debate in Progress...',
        resultsAppearHere: 'Your classification results will appear here.',
        analyzeBookCover: 'Analyze Book Cover',
        analyzeBookCoverDesc: 'Upload an image for automatic text extraction',
        quizTitle: 'DDC Quiz',
        practiceTitle: 'Live Practice',
        ddcReferenceTitle: 'DDC Reference',
        helpTitle: 'Help',
        selectLanguageTitle: 'Select Language',
        toggleThemeTitle: 'Toggle Theme',
        aiChatTitle: 'AI Chat',
        historyTitle: 'History',
        constructorTitle: 'Constructor',
        suggestTitle: 'Suggest Subjects',
        insightsTitle: 'Insights',
        contactTitle: 'Contact',
        feedbackTitle: 'Feedback',
        phone: 'Phone',
        email: 'Email',
        referenceContentPlaceholder: 'DDC reference materials would be displayed here.',
        helpContentPlaceholder: 'Help and documentation would be displayed here.',
        feedbackType: "Feedback Type",
        yourName: "Your Name (Optional)",
        message: "Message",
        submitFeedback: "Submit Feedback",
        feedbackTypeBug: "Bug Report",
        feedbackTypeSuggestion: "Suggestion",
        feedbackTypePraise: "Praise",
        feedbackTypeOther: "Other",
        feedbackPlaceholder: "Tell us what you think...",
        feedbackThankYou: "Thank You!",
        feedbackSubmitSuccess: "Your feedback has been successfully sent. We appreciate you taking the time to help us improve!",
        feedbackSubmitError: "Oops! Something went wrong while sending your feedback. Please try again later.",
        feedbackConfigError: "The feedback service is not configured. Please contact the administrator to set up the required API keys.",
        classificationHistory: "Classification History",
        emptyHistory: "Your classification history is empty.",
        clearHistory: "Clear History",
        modeGenerate: "Generate DDC",
        modeVerify: "Verify DDC",
    },
    ur: {
        deweyBrain: 'ڈیوی برین',
        accessKeyTitle: '🔑 رسائی کلید درج کریں',
        accessKeySubtitle: 'جاری رکھنے کے لیے اپنا 4 ہندسوں کا رسائی کوڈ درج کریں۔',
        appTitle: 'ڈیوی برین انٹرایکٹو',
        appSubtitle: 'ذہین ڈی ڈی سی درجہ بندی اسسٹنٹ',
        tabGenerate: 'DDC بنائیں',
        tabVerify: 'DDC کی تصدیق کریں',
        ddcEdition: 'DDC ایڈیشن',
        autoDetect: 'خودکار شناخت',
        titleSubject: 'عنوان / موضوع',
        titlePlaceholder: 'مثلاً، جرمنی میں کیمسٹری کی تاریخ',
        ddcNumberToVerify: 'تصدیق کے لیے DDC نمبر',
        ddcPlaceholder: 'مثلاً، 540.943',
        instructionHint: 'ہدایت یا اشارہ',
        hintPlaceholder: 'مثلاً، تحقیقی مقالہ، پاکستان پر توجہ مرکوز کریں',
        generateDDCNumber: '✨ DDC نمبر بنائیں',
        verifyDDCNumber: '✔️ DDC نمبر کی تصدیق کریں',
        clear: 'صاف کریں',
        analyzing: 'تجزیہ کیا جا رہا ہے...',
        fetchingLOD: 'لائبریری ڈیٹا حاصل کیا جا رہا ہے...',
        debating: 'AI بحث جاری ہے...',
        resultsAppearHere: 'آپ کی درجہ بندی کے نتائج یہاں ظاہر ہوں گے۔',
        analyzeBookCover: 'کتاب کے سرورق کا تجزیہ کریں',
        analyzeBookCoverDesc: 'خودکار متن نکالنے کے لیے تصویر اپ لوڈ کریں۔',
        quizTitle: 'DDC کوئز',
        practiceTitle: 'لائیو پریکٹس',
        ddcReferenceTitle: 'DDC حوالہ',
        helpTitle: 'مدد',
        selectLanguageTitle: 'زبان منتخب کریں',
        toggleThemeTitle: 'تھیم تبدیل کریں',
        aiChatTitle: 'AI چیٹ',
        historyTitle: 'تاریخچہ',
        constructorTitle: 'کنسٹرکٹر',
        suggestTitle: 'موضوعات تجویز کریں',
        insightsTitle: 'بصیرت',
        contactTitle: 'رابطہ',
        feedbackTitle: 'رائے',
        phone: 'فون',
        email: 'ای میل',
        feedbackType: "رائے کی قسم",
        yourName: "آپ کا نام (اختیاری)",
        message: "پیغام",
        submitFeedback: "رائے جمع کروائیں",
        feedbackTypeBug: "بگ رپورٹ",
        feedbackTypeSuggestion: "تجویز",
        feedbackTypePraise: "تعریف",
        feedbackTypeOther: "دیگر",
        feedbackPlaceholder: "ہمیں بتائیں کہ آپ کیا سوچتے ہیں...",
        feedbackThankYou: "شکریہ!",
        feedbackSubmitSuccess: "آپ کی رائے کامیابی کے ساتھ بھیج دی گئی ہے۔ ہم بہتر بنانے میں ہماری مدد کرنے کے لیے وقت نکالنے پر آپ کی تعریف کرتے ہیں!",
        feedbackSubmitError: "افوہ! آپ کی رائے بھیجتے وقت کچھ غلط ہو گیا۔ براہ کرم بعد میں دوبارہ کوشش کریں۔",
        feedbackConfigError: "فیڈ بیک سروس کنفیگر نہیں ہے۔ براہ کرم مطلوبہ API کیز سیٹ اپ کرنے کے لیے منتظم سے رابطہ کریں۔",
        classificationHistory: "درجہ بندی کی تاریخ",
        emptyHistory: "آپ کی درجہ بندی کی تاریخ خالی ہے۔",
        clearHistory: "تاریخ صاف کریں",
        modeGenerate: "DDC بنائیں",
        modeVerify: "DDC کی تصدیق کریں",
    },
    ar: {
        deweyBrain: 'ديوي برين',
        accessKeyTitle: '🔑 أدخل مفتاح الوصول',
        accessKeySubtitle: 'أدخل رمز الوصول المكون من 4 أرقام للمتابعة.',
        appTitle: 'ديوي برين التفاعلي',
        appSubtitle: 'مساعد تصنيف ديوي العشري الذكي',
        tabGenerate: 'إنشاء DDC',
        tabVerify: 'التحقق من DDC',
        ddcEdition: 'إصدار DDC',
        autoDetect: 'اكتشاف تلقائي',
        titleSubject: 'العنوان / الموضوع',
        titlePlaceholder: 'على سبيل المثال، تاريخ الكيمياء في ألمانيا',
        ddcNumberToVerify: 'رقم DDC للتحقق',
        ddcPlaceholder: 'على سبيل المثال، 540.943',
        instructionHint: 'تعليمات أو تلميح',
        hintPlaceholder: 'على سبيل المثال، ورقة بحثية، التركيز على باكستان',
        generateDDCNumber: '✨ إنشاء رقم DDC',
        verifyDDCNumber: '✔️ التحقق من رقم DDC',
        clear: 'مسح',
        analyzing: 'يتم التحليل...',
        fetchingLOD: 'جارٍ جلب بيانات المكتبة...',
        debating: 'مناقشة الذكاء الاصطناعي جارية...',
        resultsAppearHere: 'ستظهر نتائج التصنيف الخاصة بك هنا.',
        analyzeBookCover: 'تحليل غلاف الكتاب',
        analyzeBookCoverDesc: 'تحميل صورة لاستخراج النص تلقائيا',
        quizTitle: 'اختبار DDC',
        practiceTitle: 'ممارسة حية',
        ddcReferenceTitle: 'مرجع DDC',
        helpTitle: 'مساعدة',
        selectLanguageTitle: 'اختار اللغة',
        toggleThemeTitle: 'تبديل السمة',
        aiChatTitle: 'دردشة AI',
        historyTitle: 'التاريخ',
        constructorTitle: 'المنشئ',
        suggestTitle: 'اقترح مواضيع',
        insightsTitle: 'رؤى',
        contactTitle: 'اتصل',
        feedbackTitle: 'ردود الفعل',
        phone: 'هاتف',
        email: 'بريد إلكتروني',
        feedbackType: "نوع الملاحظات",
        yourName: "اسمك (اختياري)",
        message: "رسالة",
        submitFeedback: "إرسال الملاحظات",
        feedbackTypeBug: "تقرير خطأ",
        feedbackTypeSuggestion: "اقتراح",
        feedbackTypePraise: "مدح",
        feedbackTypeOther: "آخر",
        feedbackPlaceholder: "أخبرنا برأيك...",
        feedbackThankYou: "شكرا لك!",
        feedbackSubmitSuccess: "تم إرسال ملاحظاتك بنجاح. نحن نقدر وقتك لمساعدتنا على التحسين!",
        feedbackSubmitError: "عفوًا! حدث خطأ ما أثناء إرسال ملاحظاتك. يرجى المحاولة مرة أخرى في وقت لاحق.",
        feedbackConfigError: "خدمة الملاحظات ليست مهيأة. يرجى الاتصال بالمسؤول لإعداد مفاتيح API المطلوبة.",
        classificationHistory: "سجل التصنيف",
        emptyHistory: "سجل التصنيف الخاص بك فارغ.",
        clearHistory: "مسح السجل",
        modeGenerate: "إنشاء DDC",
        modeVerify: "التحقق من DDC",
    },
    fr: {
        deweyBrain: 'Dewey Brain',
        appTitle: 'Dewey Brain Interactif',
        appSubtitle: 'Assistant de classification DDC intelligent',
        tabGenerate: 'Générer DDC',
        tabVerify: 'Vérifier DDC',
        titleSubject: 'Titre / Sujet',
        titlePlaceholder: 'ex: Une histoire de la chimie en Allemagne',
        generateDDCNumber: '✨ Générer le numéro DDC',
        clear: 'Effacer',
        resultsAppearHere: 'Vos résultats de classification apparaîtront ici.',
        quizTitle: 'Quiz DDC',
        practiceTitle: 'Pratique en direct',
        ddcReferenceTitle: 'Référence DDC',
        helpTitle: 'Aide',
        selectLanguageTitle: 'Choisir la langue',
        toggleThemeTitle: 'Changer de thème',
        aiChatTitle: 'Chat IA',
        historyTitle: 'Histoire',
        constructorTitle: 'Constructeur',
        suggestTitle: 'Suggérer',
        insightsTitle: 'Aperçus',
        contactTitle: 'Contact',
        feedbackTitle: 'Retour',
        phone: 'Téléphone',
        email: 'Email',
        feedbackType: "Type de retour",
        yourName: "Votre nom (facultatif)",
        message: "Message",
        submitFeedback: "Envoyer les commentaires",
        feedbackTypeBug: "Rapport de bogue",
        feedbackTypeSuggestion: "Suggestion",
        feedbackTypePraise: "Éloge",
        feedbackTypeOther: "Autre",
        feedbackPlaceholder: "Dites-nous ce que vous en pensez...",
        feedbackThankYou: "Merci !",
        feedbackSubmitSuccess: "Vos commentaires ont été envoyés avec succès. Nous vous remercions de prendre le temps de nous aider à nous améliorer !",
        feedbackSubmitError: "Oups ! Une erreur s'est produite lors de l'envoi de vos commentaires. Veuillez réessayer plus tard.",
        feedbackConfigError: "Le service de feedback n'est pas configuré. Veuillez contacter l'administrateur pour configurer les clés API requises.",
        classificationHistory: "Historique de classification",
        emptyHistory: "Votre historique de classification est vide.",
        clearHistory: "Effacer l'historique",
        modeGenerate: "Générer DDC",
        modeVerify: "Vérifier DDC",
    },
    es: {
        deweyBrain: 'Dewey Brain',
        appTitle: 'Dewey Brain Interactivo',
        appSubtitle: 'Asistente inteligente de clasificación DDC',
        tabGenerate: 'Generar DDC',
        tabVerify: 'Verificar DDC',
        titleSubject: 'Título / Asunto',
        titlePlaceholder: 'ej: Una historia de la química en Alemania',
        generateDDCNumber: '✨ Generar número DDC',
        clear: 'Limpiar',
        resultsAppearHere: 'Sus resultados de clasificación aparecerán aquí.',
        quizTitle: 'Prueba DDC',
        practiceTitle: 'Práctica en vivo',
        ddcReferenceTitle: 'Referencia DDC',
        helpTitle: 'Ayuda',
        selectLanguageTitle: 'Seleccionar idioma',
        toggleThemeTitle: 'Cambiar tema',
        aiChatTitle: 'Chat de IA',
        historyTitle: 'Historial',
        constructorTitle: 'Constructor',
        suggestTitle: 'Sugerir',
        insightsTitle: 'Perspectivas',
        contactTitle: 'Contacto',
        feedbackTitle: 'Comentarios',
        phone: 'Teléfono',
        email: 'Correo electrónico',
        feedbackType: "Tipo de comentario",
        yourName: "Tu nombre (opcional)",
        message: "Mensaje",
        submitFeedback: "Enviar comentarios",
        feedbackTypeBug: "Reporte de error",
        feedbackTypeSuggestion: "Sugerencia",
        feedbackTypePraise: "Elogio",
        feedbackTypeOther: "Otro",
        feedbackPlaceholder: "Dinos lo que piensas...",
        feedbackThankYou: "¡Gracias!",
        feedbackSubmitSuccess: "Sus comentarios han sido enviados con éxito. ¡Agradecemos que se tome el tiempo para ayudarnos a mejorar!",
        feedbackSubmitError: "¡Ups! Algo salió mal al enviar sus comentarios. Por favor, inténtelo de nuevo más tarde.",
        feedbackConfigError: "El servicio de comentarios no está configurado. Póngase en contacto con el administrador para configurar las claves de API necesarias.",
        classificationHistory: "Historial de clasificación",
        emptyHistory: "Tu historial de clasificación está vacío.",
        clearHistory: "Borrar historial",
        modeGenerate: "Generar DDC",
        modeVerify: "Verificar DDC",
    },
    zh: {
        deweyBrain: '杜威大脑',
        appTitle: '杜威大脑互动',
        appSubtitle: '智能DDC分类助手',
        tabGenerate: '生成DDC',
        tabVerify: '验证DDC',
        titleSubject: '标题/主题',
        titlePlaceholder: '例如，德国化学史',
        generateDDCNumber: '✨ 生成DDC编号',
        clear: '清除',
        resultsAppearHere: '您的分类结果将显示在此处。',
        quizTitle: 'DDC测验',
        practiceTitle: '现场练习',
        ddcReferenceTitle: 'DDC参考',
        helpTitle: '帮助',
        selectLanguageTitle: '选择语言',
        toggleThemeTitle: '切换主题',
        aiChatTitle: 'AI聊天',
        historyTitle: '历史',
        constructorTitle: '构造器',
        suggestTitle: '建议',
        insightsTitle: '见解',
        contactTitle: '联系',
        feedbackTitle: '反馈',
        phone: '电话',
        email: '电子邮件',
        feedbackType: "反馈类型",
        yourName: "您的姓名（可选）",
        message: "信息",
        submitFeedback: "提交反馈",
        feedbackTypeBug: "错误报告",
        feedbackTypeSuggestion: "建议",
        feedbackTypePraise: "表扬",
        feedbackTypeOther: "其他",
        feedbackPlaceholder: "告诉我们您的想法...",
        feedbackThankYou: "谢谢！",
        feedbackSubmitSuccess: "您的反馈已成功发送。我们感谢您抽出宝贵时间帮助我们改进！",
        feedbackSubmitError: "哎呀！发送您的反馈时出了点问题。请稍后再试。",
        feedbackConfigError: "反馈服务未配置。请联系管理员设置所需的API密钥。",
        classificationHistory: "分类历史",
        emptyHistory: "您的分类历史是空的。",
        clearHistory: "清除历史",
        modeGenerate: "生成DDC",
        modeVerify: "验证DDC",
    }
};